### PR TITLE
Created basic reference parsing #2

### PR DESCRIPTION
**Pull request by joshpetit**
Hey, I came across this repo because I needed a reference parser for a [module](https://github.com/joshpetit/biblehub) I'm developing (working on release two on dev branch!). I am so glad someone already implemented one so well! Anyways, here's what I did:

- Created basic reference parsing with a regex (not a long/defined one but passed the possible tests)
- Added passages_from_string to README
- Did a few grammar/linting fixes

If there's anything else that's needed I'm glad to continue working on the parse function so that it can reach some of the goals you set for it!

### CODE REVIEW

**Comment by col16** [comment]
Thanks Josh, that sounds great! I'll have a look at it when I get some time (hopefully later this week).

**Comment by joshpetit** [comment]
Hey! Hope you're doing well. Have you been able to look at the pr? No rush!

**Comment by col16** [comment]
Thanks for your work in putting together this regex. A few comments...

- I prefer using `r` at the start of the string so that you don't have to have double backslashes
- I prefer using the `re.IGNORECASE` flag rather than including both uppercase A-Z and lowercase a-z
- In `[A-Za-z, ]` we don't need to match commas (if you disagree, add a unit test to show how they would be used)
- re.match matches at the start of a string, so `^` isn't necessary
- Finding passages within other text is too difficult for now, so let's add $ to the end so that it fails if anything else follows the reference
- As it stands this would match something with a space at the start, e.g. " Gen". I suppose this isn't all bad, but I'm keen to stick with the strict approach for now.
- As it stands this would match "Gen :1" or "Gen -1".
- I'd like to be able to match "Gen 1:1-2:4" (i.e. a passage with an ending verse).
- I'm a fan of named groups.

I've had a go and I'll push my version to the PR in a moment. Hope you don't get offended by the fact that I've completely re-worked things! And sorry for taking so long.

**Review by joshpetit — COMMENTED** [review]
This is really awesome! I'm not a pro at regexes so I'm really glad you did this. Motivates me to learn more about regexes!

**Comment by col16** [comment]
Happy for me to merge the pull request then? Just wanted to check in case there was anything you wanted to change.

And thanks heaps for your help with this--parsing was a feature that I never got around to adding, so it's nice to have it done.

**Comment by joshpetit** [comment]
Yep seems good to merge! Thanks for taking a look at it!

**Pull request merged**
